#!/usr/bin/env python3
"""
Generates the site's pixel cursors.  python3 tools/cursors.py

These are drawn from scratch -- deliberately NOT traced from Apple's cursors,
which are Susan Kare's copyrighted artwork. A plain pixel arrow is a generic
functional shape (Amiga, Atari ST, Windows 3.1 and X11 all shipped their own),
so an original drawing in that idiom is ours to use.

Writes 1x and 2x PNGs into assets/img/cursors/ plus a CSS partial.
"""
import os
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'assets', 'img', 'cursors')
os.makedirs(OUT, exist_ok=True)

WHITE = (244, 244, 242, 255)
BLACK = (8, 8, 9, 255)
CLEAR = (0, 0, 0, 0)

ARROW = [
    "X..........",
    "XX.........",
    "XXX........",
    "XXXX.......",
    "XXXXX......",
    "XXXXXX.....",
    "XXXXXXX....",
    "XXXXXXXX...",
    "XXXXXXXXX..",
    "XXXXXXXXXX.",
    "XXXXXX.....",
    "XXX.XXX....",
    "XX..XXX....",
    "X....XXX...",
    ".....XXX...",
    "......XX...",
]

# a pointing hand for anything clickable. The 1px gaps between finger columns
# get filled by the auto-outline pass, which is what draws the knuckle lines --
# without them the silhouette reads as a lollipop at this size.
HAND = [
    "...XX........",
    "...XX........",
    "...XX........",
    "...XX........",
    "...XX........",
    "...XX.XX.....",
    "...XX.XX.XX..",
    "...XX.XX.XX..",
    "XX.XX.XX.XX..",
    "XXXXXXXXXXX..",
    "XXXXXXXXXXX..",
    "XXXXXXXXXXX..",
    ".XXXXXXXXXX..",
    ".XXXXXXXXXX..",
    "..XXXXXXXX...",
]

# a loupe, for the dithered plates -- it means "click to see this bigger"
LOUPE = [
    "...XXXXX....",
    "..X.....X...",
    ".X.......X..",
    "X.........X.",
    "X.........X.",
    "X.........X.",
    "X.........X.",
    ".X.......X..",
    "..X.....X...",
    "...XXXXX....",
    "......XXX...",
    ".......XXX..",
    "........XXX.",
    ".........XX.",
]


def render(grid):
    """Fill in white, then wrap every filled pixel in a black outline so the
    cursor stays visible over both the near-black ground and a bright photo."""
    h, w = len(grid), len(grid[0])
    W, H = w + 2, h + 2                      # room for the outline
    img = Image.new('RGBA', (W, H), CLEAR)
    px = img.load()
    solid = {(x + 1, y + 1) for y, row in enumerate(grid)
             for x, c in enumerate(row) if c == 'X'}
    for x, y in solid:
        px[x, y] = WHITE
    for x, y in list(solid):
        for dx in (-1, 0, 1):
            for dy in (-1, 0, 1):
                n = (x + dx, y + dy)
                if n not in solid and 0 <= n[0] < W and 0 <= n[1] < H:
                    px[n[0], n[1]] = BLACK
    return img


# name -> (grid, hotspot x, hotspot y) measured on the OUTLINED image
CURSORS = {
    'arrow': (ARROW, 1, 1),
    'hand':  (HAND, 5, 1),
    'loupe': (LOUPE, 6, 6),
}

css = ['/* ---------- pixel cursors (generated by tools/cursors.py) ---------- */',
       ':root{']
for name, (grid, hx, hy) in CURSORS.items():
    img = render(grid)
    img.save(f'{OUT}/{name}.png')
    img.resize((img.width * 2, img.height * 2), Image.NEAREST).save(f'{OUT}/{name}@2x.png')
    p1, p2 = f'assets/img/cursors/{name}.png', f'assets/img/cursors/{name}@2x.png'
    css.append(f'  --cur-{name}: -webkit-image-set(url("../img/cursors/{name}.png") 1x, '
               f'url("../img/cursors/{name}@2x.png") 2x) {hx} {hy},'
               f' url("../img/cursors/{name}.png") {hx} {hy}')
    print(f'  {name:6s} {img.size}  hotspot ({hx},{hy})')
css[-1] = css[-1] + ';'
css = [css[0], css[1]] + [c + ';' if not c.endswith(';') else c for c in css[2:]]
css.append('}')
css += [
 '',
 '/* the whole page gets the arrow; anything clickable gets the hand */',
 'body{cursor: var(--cur-arrow), auto}',
 'a, button, .kbd, .role, .chip, .clockwrap, .lb-x, summary, [role="button"]',
 '  {cursor: var(--cur-hand), pointer}',
 '.role.soon, .btn.inert{cursor: var(--cur-arrow), default}',
 '/* a loupe over the dithered plates: they open in the lightbox */',
 '.plate, .plate *{cursor: var(--cur-loupe), zoom-in}',
 '/* never override a text caret */',
 'input, textarea{cursor: text}',
 '',
 '@media (hover: none), (pointer: coarse){',
 '  body, a, button, .kbd, .role, .chip, .clockwrap, .lb-x,',
 '  .plate, .plate *{cursor: auto}',
 '}',
 '',
]
open(os.path.join(ROOT, 'assets', 'css', 'cursors.css'), 'w').write('\n'.join(css) + '\n')
print('\nassets/css/cursors.css written')
